- name: Get block devices
  command: /usr/bin/bash -c 'lsblk -o NAME,MOUNTPOINT --json > /tmp/devices.json'

- name: Get root disk name
  command: jq '.blockdevices[] | select(.children[]?.mountpoint == "/") | .name' /tmp/devices.json
  register: root_disk_name

- name: Show root disk name
  debug:
    var: root_disk_name

- name: Get non-root disk name
  detect_non_root_disk:
      devices: "{{ ansible_devices }}"
      root_partion_disk: "{{ root_disk_name.stdout }}"
  register: nonroot_disk
  failed_when: nonroot_disk.stdout == 'NOT_FOUND'

- name: Debug nonroot disk name
  debug:
    var: nonroot_disk